### PR TITLE
Fix: feat/Phone-Validation-both-patient-and-doctor

### LINKED ISSUE #26: [Feature] Add Validation for Mobile Number in Signup Form
### Issue Description:
Currently, the signup form does not validate the mobile number format (even 8 digit mobile number will proceed with signup) and only enforces a basic password length requirement (minimum of 6 characters). This leads to potential issues where users can sign up with invalid mobile numbers or weak passwords. To enhance security and data integrity, we need to:
1. Add proper validation for the mobile number format.
2. Enhance password validation to meet more robust security standards.

### Expected Behavior:

1. **Mobile Number Validation**:
   - The mobile number must be exactly 10 digits long (or as per the required format).
   - The frontend should validate the mobile number format before submission, and the backend should ensure that the mobile number is in the correct format before processing the signup request.

2. **Password Validation**:
   - The password must be at least 8 characters long.
   - The password must contain at least one uppercase letter.
   - The password must contain at least one lowercase letter.
   - The password must contain at least one numeric digit.
   - The password must contain at least one special character (e.g., `!@#$%^&*`).

3. **Frontend**:
   - If the mobile number is invalid (e.g., incorrect format or length), an error message should be displayed, and the form should not be submitted.
   - If the password does not meet the validation criteria, an error message should be displayed, and the form should not be submitted.

4. **Backend**:
   - Upon receiving the signup request, the server should verify that both the mobile number and password meet the required validation criteria.
   - If the mobile number is invalid or the password does not meet the required standards, the server should reject the request with appropriate error messages.

By implementing these validations, we will improve both the user experience and the security of the application.

Here below is the issue of the video..

https://github.com/user-attachments/assets/b6ac8930-ff28-424f-8cd5-c0123c8b62ec

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/PratikMane0112/TelMedSphere/blob/master/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a SWOC'25 contributor.
- [X] I am a KWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/PratikMane0112/TelMedSphere/blob/master/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by dpgaharwal**
### **Fixes Issue🛠️**
Closes #26

---

### **Description👨‍💻**

- Implemented **mobile number validation** in the signup form to ensure that only valid 10-digit phone numbers are accepted.
- Updated the **handleFormSubmit** function to check for a valid phone number before form submission. 
- Added logic to handle both valid and invalid mobile numbers:
  - **Valid mobile numbers** (exactly 10 digits) proceed with the form submission.
  - **Invalid mobile numbers** (less than 10 digits or containing non-numeric characters) show an error message and prevent submission.

Verified the input for both **valid** and **non-valid** forms to ensure that the validation works as expected:
  - Valid form input should proceed to backend.
  - Invalid form input should show appropriate error messages.

---

### **Type of Change📄**

- [ ] Bug fix (non-breaking change which fixes a bug)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Style (non-breaking change which improves website style or formatting)
- [ ] Documentation (non-breaking change which updates or adds documentation)
- [ ] Responsiveness (non-breaking change which improves UI/UX on different screen sizes)

---

### **Checklist✅**

- [x] I am an Open Source contributor
- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project
- [x] I have commented on my code, particularly in hard-to-understand areas

---

### **Video📷**

https://github.com/user-attachments/assets/63df9893-80ae-489b-94e1-a8c6e9f013b2

---

### CODE REVIEW

**Review by PratikMane0112 — CHANGES_REQUESTED** [review]
Deleted files

**Review by PratikMane0112 — COMMENTED** [review]
.env file deleted from frontend as well as backend .......

**Comment by dpgaharwal** [comment]
I just chaned the Accountform.jsx file of frontend.
All the files changed due to installation of dependency

**Comment by PratikMane0112** [comment]
Hey, you want just PR getting merged. then please do some changes in README file on new branch I will merged it

**Comment by PratikMane0112** [comment]
Also, bro you have have added form validation with simple windows, website of react framework it doesnt match with tech stack

**Comment by dpgaharwal** [comment]
What should I qrite in readme file

**Comment by PratikMane0112** [comment]
Ads any emoji, dont do cahnges on local branch do directly from github

**Comment by PratikMane0112** [comment]
and please delete the msg from SWoC server, you want PR for KWoC right ?

**Comment by dpgaharwal** [comment]
Yes,and
Wouldd i creat readme file and commint in the same pr

**Comment by PratikMane0112** [comment]
Create a new from other branch

**Comment by PratikMane0112** [comment]
And also delete all this chatting

**Comment by PratikMane0112** [comment]
Hey @dpgaharwal, please follow the guidelines & teck stack of porject

**Pull request closed without merging**
